use super::grant::{Grant, SignedGrant};
use crate::protocol::{decode, encode};
use ed25519_dalek::{Signer, SigningKey};
use rand::rngs::OsRng;
use serde::{Deserialize, Serialize};
use snow::{
  params::DHChoice,
  resolvers::{CryptoResolver, DefaultResolver},
};
use std::{
  fs::{self, File, OpenOptions},
  io::{Read, Write},
  path::Path,
};
use zeroize::Zeroizing;

pub(super) const NOISE_PROTOCOL: &str = "Noise_IK_25519_ChaChaPoly_BLAKE2s";

/// A local X25519 identity. Debug and serialization intentionally omit secrets.
#[derive(Clone)]
pub struct NoiseIdentity {
  secret: Zeroizing<[u8; 32]>,
  public: [u8; 32],
}

impl NoiseIdentity {
  pub fn generate() -> Result<Self, String> {
    let pair = snow::Builder::new(
      NOISE_PROTOCOL
        .parse()
        .map_err(|e| format!("Invalid Noise protocol: {e}"))?,
    )
    .generate_keypair()
    .map_err(|e| format!("Could not generate Noise identity: {e}"))?;
    let secret = Zeroizing::new(pair.private);
    Self::from_secret(
      secret
        .as_slice()
        .try_into()
        .map_err(|_| "Invalid generated private key")?,
    )
  }

  fn from_secret(secret: [u8; 32]) -> Result<Self, String> {
    let secret = Zeroizing::new(secret);
    let mut dh = DefaultResolver
      .resolve_dh(&DHChoice::Curve25519)
      .ok_or("X25519 is unavailable")?;
    dh.set(secret.as_ref());
    let public = dh.pubkey().try_into().map_err(|_| "Invalid X25519 public key")?;
    Ok(Self { secret, public })
  }

  /// Create a private file once, or load an existing regular, owner-only file.
  pub fn load_or_create(path: &Path) -> Result<Self, String> {
    let secret = load_or_create_secret(path, "noise_x25519", || {
      let identity = Self::generate()?;
      Ok(*identity.secret)
    })?;
    Self::from_secret(*secret)
  }

  pub fn public_key(&self) -> String {
    encode(&self.public)
  }

  pub fn private_key(&self) -> &[u8; 32] {
    &self.secret
  }
}

/// An owner-controlled signing identity, distinct from every transport key.
#[derive(Clone)]
pub struct OwnerIdentity(SigningKey);

impl OwnerIdentity {
  pub fn generate() -> Self {
    Self(SigningKey::generate(&mut OsRng))
  }

  pub fn load_or_create(path: &Path) -> Result<Self, String> {
    let secret = load_or_create_secret(path, "owner_ed25519", || Ok(Self::generate().0.to_bytes()))?;
    Ok(Self(SigningKey::from_bytes(&secret)))
  }

  pub fn public_key(&self) -> String {
    encode(self.0.verifying_key().as_bytes())
  }

  /// Sign the exact typed grant; callers choose scope and expiry explicitly.
  pub fn sign_grant(&self, grant: Grant) -> Result<SignedGrant, String> {
    let signature = encode(&self.0.sign(&grant.signing_bytes()?).to_bytes());
    let signed = SignedGrant { grant, signature };
    signed.validate()?;
    Ok(signed)
  }
}

/// Public keys use canonical unpadded URL-safe base64, always exactly 32 bytes.
pub fn decode_public_key(value: &str) -> Result<[u8; 32], String> {
  if value.len() != 43 {
    return Err("Public key must be 32 bytes in unpadded URL-safe base64".into());
  }
  let bytes: [u8; 32] = decode(value, 32)?.try_into().map_err(|_| "Invalid public key length")?;
  if encode(&bytes) != value || bytes == [0; 32] {
    return Err("Invalid public key".into());
  }
  Ok(bytes)
}

/// Reject low-order X25519 points before using them as authorization identities.
/// A fixed, nonsecret clamped scalar is sufficient for this public point check:
/// low-order inputs yield an all-zero X25519 result. Session key agreement still
/// belongs entirely to Noise, with fresh secrets generated by its resolver.
pub(super) fn decode_noise_public_key(value: &str) -> Result<[u8; 32], String> {
  let bytes = decode_public_key(value)?;
  let mut dh = DefaultResolver
    .resolve_dh(&DHChoice::Curve25519)
    .ok_or("X25519 is unavailable")?;
  dh.set(&[0x42; 32]);
  let mut result = [0; 32];
  dh.dh(&bytes, &mut result).map_err(|_| "Invalid X25519 public key")?;
  if result == [0; 32] {
    return Err("Low-order X25519 public keys are not permitted".into());
  }
  Ok(bytes)
}

#[derive(Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
struct SecretFile {
  version: u8,
  kind: String,
  secret_key: String,
}

impl Drop for SecretFile {
  fn drop(&mut self) {
    use zeroize::Zeroize;
    self.secret_key.zeroize();
  }
}

fn load_or_create_secret(
  path: &Path,
  kind: &str,
  generate: impl FnOnce() -> Result<[u8; 32], String>,
) -> Result<Zeroizing<[u8; 32]>, String> {
  if let Some(parent) = path.parent().filter(|parent| !parent.as_os_str().is_empty()) {
    fs::create_dir_all(parent).map_err(|e| format!("Could not create identity directory: {e}"))?;
  }
  // create_new is exclusive and rejects a pre-existing symlink. On reads,
  // O_NOFOLLOW closes the final-component symlink inspection/open race.
  let mut options = OpenOptions::new();
  options.write(true).create_new(true);
  #[cfg(unix)]
  {
    use std::os::unix::fs::OpenOptionsExt;
    options.mode(0o600).custom_flags(libc::O_NOFOLLOW);
  }
  match options.open(path) {
    Ok(mut file) => {
      let secret = Zeroizing::new(generate()?);
      let encoded = Zeroizing::new(
        serde_json::to_vec(&SecretFile {
          version: 1,
          kind: kind.into(),
          secret_key: encode(secret.as_ref()),
        })
        .map_err(|e| e.to_string())?,
      );
      file
        .write_all(&encoded)
        .and_then(|_| file.sync_all())
        .map_err(|e| format!("Could not save private identity: {e}"))?;
      Ok(secret)
    }
    Err(error) if error.kind() == std::io::ErrorKind::AlreadyExists => read_secret(path, kind),
    Err(error) => Err(format!("Could not create private identity: {error}")),
  }
}

fn read_secret(path: &Path, kind: &str) -> Result<Zeroizing<[u8; 32]>, String> {
  let metadata = fs::symlink_metadata(path).map_err(|e| format!("Could not inspect private identity: {e}"))?;
  if !metadata.is_file() {
    return Err("Private identity must be a regular file, not a symlink".into());
  }
  let mut options = OpenOptions::new();
  options.read(true);
  #[cfg(unix)]
  {
    use std::os::unix::fs::OpenOptionsExt;
    options.custom_flags(libc::O_NOFOLLOW | libc::O_NONBLOCK);
  }
  let mut file = options
    .open(path)
    .map_err(|e| format!("Could not open private identity: {e}"))?;
  validate_private_file(&file)?;
  let mut bytes = Zeroizing::new(Vec::new());
  (&mut file)
    .take(4097)
    .read_to_end(&mut bytes)
    .map_err(|e| format!("Could not read private identity: {e}"))?;
  if bytes.len() > 4096 {
    return Err("Private identity file is too large".into());
  }
  let stored: SecretFile = serde_json::from_slice(&bytes).map_err(|_| "Invalid private identity file")?;
  if stored.version != 1 || stored.kind != kind {
    return Err("Private identity has the wrong version or key kind".into());
  }
  let secret = Zeroizing::new(decode(&stored.secret_key, 32)?);
  Ok(Zeroizing::new(
    secret
      .as_slice()
      .try_into()
      .map_err(|_| "Invalid private identity key length")?,
  ))
}

fn validate_private_file(file: &File) -> Result<(), String> {
  let metadata = file
    .metadata()
    .map_err(|e| format!("Could not inspect opened private identity: {e}"))?;
  if !metadata.is_file() || metadata.len() > 4096 {
    return Err("Private identity must be a small regular file".into());
  }
  #[cfg(unix)]
  {
    use std::os::unix::fs::MetadataExt;
    if metadata.mode() & 0o777 != 0o600 || metadata.nlink() != 1 {
      return Err("Private identity must have mode 0600 and no hard links".into());
    }
    // SAFETY: geteuid has no arguments, allocation, or memory side effects.
    if metadata.uid() != unsafe { libc::geteuid() } {
      return Err("Private identity must be owned by the current user".into());
    }
  }
  Ok(())
}

#[cfg(test)]
mod tests {
  use super::*;

  #[test]
  fn identities_round_trip_and_key_kinds_cannot_be_confused() {
    let directory = tempfile::tempdir().unwrap();
    let noise_path = directory.path().join("noise.json");
    let owner_path = directory.path().join("owner.json");
    let noise = NoiseIdentity::load_or_create(&noise_path).unwrap();
    let owner = OwnerIdentity::load_or_create(&owner_path).unwrap();
    assert_eq!(
      noise.public_key(),
      NoiseIdentity::load_or_create(&noise_path).unwrap().public_key()
    );
    assert_eq!(
      owner.public_key(),
      OwnerIdentity::load_or_create(&owner_path).unwrap().public_key()
    );
    assert!(OwnerIdentity::load_or_create(&noise_path).is_err());
    assert!(NoiseIdentity::load_or_create(&owner_path).is_err());
  }

  #[test]
  fn noise_identities_reject_low_order_public_points() {
    let mut point_one = [0; 32];
    point_one[0] = 1;
    assert!(decode_noise_public_key(&encode(&point_one)).is_err());
    assert!(decode_noise_public_key(&NoiseIdentity::generate().unwrap().public_key()).is_ok());
  }

  #[cfg(unix)]
  #[test]
  fn private_identities_reject_symlinks_hardlinks_and_insecure_permissions() {
    use std::os::unix::fs::{PermissionsExt, symlink};
    let directory = tempfile::tempdir().unwrap();
    let path = directory.path().join("identity");
    NoiseIdentity::load_or_create(&path).unwrap();
    assert_eq!(fs::metadata(&path).unwrap().permissions().mode() & 0o777, 0o600);
    let link = directory.path().join("link");
    symlink(&path, &link).unwrap();
    assert!(NoiseIdentity::load_or_create(&link).is_err());
    fs::remove_file(link).unwrap();
    fs::set_permissions(&path, fs::Permissions::from_mode(0o644)).unwrap();
    assert!(NoiseIdentity::load_or_create(&path).is_err());
    fs::set_permissions(&path, fs::Permissions::from_mode(0o600)).unwrap();
    fs::hard_link(&path, directory.path().join("hardlink")).unwrap();
    assert!(NoiseIdentity::load_or_create(&path).is_err());
  }
}
